{% set name = "qcs-sdk-python" %}
{% set version = "0.12.8" %}

package:
  name: qcs-sdk-python-split
  version: {{ version }}

source:
  url: https://github.com/rigetti/qcs-sdk-rust/archive/refs/tags/python/v{{ version }}.tar.gz
  sha256: 7f2559c71d7d4955d65fd0b3b9392bc14a9db94f529b53518d3afd2d33231f86

build:
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - maturin >=1.0.0,<2.0.0
    - cargo-bundle-licenses
    - python
  host:
    - python
    - toml

outputs:
  - name: qcs-sdk-python
    script: install.sh  # [unix]
    script: install.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("qcs-sdk-python", max_pin="x.x") }}
    requirements:
      build:
        # Defines the runtime requirements for the package
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - pip
        - python
      run:
        - quil 0.5.7
        - python
      run_constrained:
        - qcs-sdk-python-grpc-web ==9999999999
    test:
      imports:
        - qcs_sdk.qcs_sdk
      requires:
      #   - cargo-make
        - pip
        - rust
      # source_files:
      #   - Cargo.toml
      commands:
        - pip check
      #   - makers

  # - Naming conversion
  - name: qcs_sdk_python
    build:
      noarch: python
    requirements:
      run:
        - qcs-sdk-python {{ version }}
    test:
      imports:
        - qcs_sdk.qcs_sdk

about:
  home: https://github.com/rigetti/qcs-sdk-rust
  summary: 'Defines the Python bindings to make use of the QCS Rust SDK.'
  description: |
    Defines the Python bindings to make use of the QCS Rust SDK.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://docs.rs/qcs/latest/qcs/

extra:
  recipe-maintainers:
    - MementoRC
  feedstock-name: qcs-sdk-python
